projectCinema/cinema/urls.py
from django.urls import path
from . import views
from .views import login_view
from django.contrib.auth import views as auth_views
from .views import edit_profile
from .views import logout_view
from .forms import CustomPasswordResetForm
from .views import PasswordChangeView


from .forms import UserLoginForm



urlpatterns = [
 path('',views.home, name="home"),
 path('search/', views.search_view,name="search"),
 path('filter/', views.filter_view,name="genre"),
#  path('registration/',views.usrreg,name="reg"),
 path('registration/', views.register, name='register'),
#   path('verify_email/<int:uid>/<str:token>/', views.verify_email, name='verify_email'),
 path('verify/<str:uidb64>/<str:token>/', views.verify_email, name='verify_email'),

 path('login/', login_view, name='login'),
 path('edit-profile/', edit_profile, name='edit_profile'),
 path('save-payment/', views.save_payment, name='save_payment'),
 path('logout/', logout_view, name='logout'),
 path('password-reset/', 
         auth_views.PasswordResetView.as_view(
             form_class=CustomPasswordResetForm,
             template_name='html/password_reset_form.html',
             email_template_name='html/password_reset_email.html',
             subject_template_name='html/password_reset_subject.txt',
             success_url='/password_reset/done/', 
         ), 
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='html/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='html/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='html/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('password/change/', PasswordChangeView.as_view(), name='password_change'),
     path('admin/', views.admin_view,name="admin"),
 path('admin/movies', views.adminmovies_view,name="admin_movies"),
 path('admin/promotions', views.adminpromotions_view,name="admin_promotions"),
 path('confirmation/', views.confirmation_view,name="confirmation"),
#  path('movies/', views.movies_view,name="movies"),
 path('payment/', views.payment_view,name="payment"),
 path('userprofile/', views.userprofile_view,name="userprofile"),
#  path('movies/', views.movie_list, name='movie_list'),
path('movies/', views.MovieListView.as_view(), name='movie-list'),
 path('mybookings/', views.my_bookings,name="my_bookings"),
#  path('movies/', views.get_movies, name='get_movies'),
path('api/movies/', views.movie_list, name='movie_list'),
path('individual_movie/<str:movie_title>/', views.individual_movie, name='individual_movie'),
path('select_time_and_seats/<str:movie_title>', views.select_time_and_seats, name='select_time_and_seats'),
path('show_seats/<str:movie_title>/<str:selected_date>/<str:show_time>/<int:show_id>/', views.show_seats, name='show_seats'),
path('book_tickets/<str:movie_title>/<str:selected_date>/<str:show_time>/<int:show_id>/', views.book_tickets, name='book_tickets'),
path('get_blocked_seats/', views.get_blocked_seats, name='get_blocked_seats'), #<------------added this
path('apply_promo/<str:movie_title>/<str:selected_date>/<str:show_time>/<int:show_id>/', views.apply_promo, name='apply_promo'),
path('payments/', views.payments, name='payments'),
path('success/',views.success, name='success'),
]

projectCinema/projectCinema/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cinema.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projectCinema/cinema/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
import random
import string
from django.core.exceptions import ValidationError
from datetime import timedelta
from django.core.validators import MinValueValidator, MaxValueValidator



class User(AbstractUser):
   # Make email, phone_number, first_name, and last_name required
    email = models.EmailField('email address', blank=False, null=False)
    phone_number = models.CharField(max_length=20, blank=False, null=False)
    first_name = models.CharField('first name', max_length=150, blank=False, null=False)
    last_name = models.CharField('last name', max_length=150, blank=False, null=False)

    photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    receive_promotions = models.BooleanField(default=False)

    CARD_CHOICES = [
        ('Visa', 'Visa'),
        ('MasterCard', 'MasterCard'),
        ('American Express', 'American Express'),
        ('Discover', 'Discover')
    ]

    credit_card_type = models.CharField(max_length=255, null=True, blank=True, choices=CARD_CHOICES, default="")
    credit_card_name = models.CharField(max_length=255, null=True, blank=True, default="")
    credit_card_number = models.CharField(max_length=20, null=True, blank=True, default="")
    credit_card_expiry = models.CharField(max_length=20, null=True, blank=True, default="")
    credit_card_cvv = models.CharField(max_length=4, null=True, blank=True, default="")
    credit_card_address = models.CharField(max_length=255, null=True, blank=True, default="")
    credit_card_city = models.CharField(max_length=255, null=True, blank=True, default="")
    credit_card_state = models.CharField(max_length=255, null=True, blank=True, default="")
    credit_card_zip = models.CharField(max_length=255, null=True, blank=True, default="")

    credit_card_type_2 = models.CharField(max_length=255, null=True, blank=True, choices=CARD_CHOICES)
    credit_card_name_2 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_number_2 = models.CharField(max_length=20, null=True, blank=True)
    credit_card_expiry_2 = models.DateField(null=True, blank=True)
    credit_card_cvv_2 = models.CharField(max_length=4, null=True, blank=True)
    credit_card_address_2 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_city_2 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_state_2 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_zip_2 = models.CharField(max_length=255, null=True, blank=True)

    credit_card_type_3 = models.CharField(max_length=255, null=True, blank=True, choices=CARD_CHOICES)
    credit_card_name_3 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_number_3 = models.CharField(max_length=20, null=True, blank=True)
    credit_card_expiry_3 = models.DateField(null=True, blank=True)
    credit_card_cvv_3 = models.CharField(max_length=4, null=True, blank=True)
    credit_card_address_3 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_city_3 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_state_3 = models.CharField(max_length=255, null=True, blank=True)
    credit_card_zip_3 = models.CharField(max_length=255, null=True, blank=True)

class Movie(models.Model):
    MPAA_RATING_CHOICES = [
        ('G', 'General Audiences'),
        ('PG', 'Parental Guidance Suggested'),
        ('PG-13', 'Parents Strongly Cautioned'),
        ('R', 'Restricted'),
        ('NC-17', 'No One 17 and Under Admitted'),
        ('NR', 'Not Rated')
    ]

    GENRE_CHOICES = [
        ('none', 'None'), 
        ('action', 'Action'),
        ('comedy', 'Comedy'),
        ('drama', 'Drama'),
        ('horror', 'Horror'),
        ('romance', 'Romance'),
        ('sci-fi', 'Science Fiction'),
    ]
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100, default='N/A')
    cast = models.CharField(max_length=1000, default='N/A')
    producer = models.CharField(max_length=100, default='N/A')
    description = models.TextField()
    release_date = models.DateField()
    duration = models.IntegerField()  # Duration in minutes
    trailer_url = models.URLField(blank=True)
    # image = models.ImageField(upload_to='img/movie_images/', null=True, blank=True)
    image = models.URLField(null=True, blank=True)
    genre = models.CharField(max_length=100, default='none')
    rating = models.CharField(max_length=5, choices=MPAA_RATING_CHOICES, default='NR')
    star_rating = models.FloatField(
        validators=[
            MinValueValidator(0.0),  # Minimum value is 0.0
            MaxValueValidator(10.0)  # Maximum value is 10.0
        ],
        default=5.0  # Default value is 5.0
    )
    def __str__(self):
        return self.title

class Screen(models.Model):
    name = models.CharField(max_length=100)
    capacity = models.IntegerField()
    def __str__(self):
        return self.name
    
class ShowBuilder:
    def __init__(self, movie, screen):
        self.movie = movie
        self.screen = screen
        self.start_time = None
        self.end_time = None
        self.price = None

    def set_show_time(self, start_time, duration):
        self.start_time = start_time
        self.end_time = start_time + timedelta(minutes=duration)
        return self

    def set_price(self, price):
        self.price = price
        return self

    def build(self):
        if not all([self.start_time, self.end_time, self.price]):
            raise ValueError("Incomplete show details provided.")
        overlapping_shows = Show.objects.filter(
            screen=self.screen,
            start_time__lt=self.end_time + timedelta(hours=1),
            end_time__gt=self.start_time
        )
        if overlapping_shows.exists():
            raise ValidationError('Another show is scheduled for this screen within 1 hour of this show\'s end time.')
        return Show.objects.create(
            movie=self.movie,
            screen=self.screen,
            start_time=self.start_time,
            end_time=self.end_time,
            price=self.price
        )
    
class Show(models.Model):
    show_id = models.CharField(max_length=10, unique=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    screen = models.ForeignKey(Screen, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    def __str__(self):
        return f"ID: {self.show_id} {self.movie.title} on Screen {self.screen} at {self.start_time}"
        # return self.show_id
    def clean(self):
        overlapping_shows = Show.objects.filter(
            screen=self.screen,
            start_time__lt=self.end_time + timedelta(hours=1),
            end_time__gt=self.end_time
        ).exclude(pk=self.pk)
        
        if overlapping_shows.exists():
            raise ValidationError('Another show is scheduled for this screen within 1 hour of this show\'s end time.')
        
class Seat(models.Model):
    # show_id = models.ForeignKey(Show, on_delete=models.CASCADE) #Added now
    show_id = models.CharField(max_length=10)
    screen = models.ForeignKey(Screen, on_delete=models.CASCADE)
    row = models.CharField(max_length=1)  # A, B, C, ...
    number = models.IntegerField()
    is_booked = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.screen} - row {self.row}"

# class Booking(models.Model):
#     STATUS_CHOICES = [
#         ('Pending', 'Pending'),
#         ('Confirmed', 'Confirmed'),
#         ('Cancelled', 'Cancelled'),
#     ]
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     show = models.ForeignKey(Show, on_delete=models.CASCADE)
#     booking_time = models.DateTimeField(auto_now_add=True)
#     total_amount = models.DecimalField(max_digits=8, decimal_places=2)
#     status = models.CharField(max_length=20, choices=STATUS_CHOICES)
#     def __str__(self):
#         return self.user

class Booking(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Cancelled', 'Cancelled'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # show = models.ForeignKey(Show, on_delete=models.CASCADE)
    show = models.CharField(max_length=2000, default=None)
    booking_time = models.DateTimeField()
    total_amount = models.DecimalField(max_digits=8, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    booking_id = models.CharField(max_length=8, unique=True)
    seats = models.CharField(max_length=2000, default=None)


    def __str__(self):
        return f"Booking ID: {self.booking_id}, User: {self.user.username}"

    # def save(self, *args, **kwargs):
    #     # Generate a random booking ID
    #     self.booking_id = ''.join(random.choices(string.digits, k=5))
    #     super().save(*args, **kwargs)

class PromoCode(models.Model):
    DISCOUNT_CHOICES = [
        ('Percentage', 'Percentage'),
        ('Fixed Amount', 'Fixed Amount'),
    ]
    code = models.CharField(max_length=20, unique=True)
    discount_type = models.CharField(max_length=20, choices=DISCOUNT_CHOICES)
    discount_value = models.DecimalField(max_digits=8, decimal_places=2)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    max_usage_count = models.IntegerField()
    current_usage_count = models.IntegerField(default=0)
    def __str__(self):
        return self.code

class PromoCodeUsage(models.Model):
    promo_code = models.ForeignKey(PromoCode, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    def __str__(self):

projectCinema/cinema/templates/html/book_tickets.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Order Summary</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index 2.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/indi_movie.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/booking.css' %}" type="text/css" />
    <script>
      window.onload = function() {
          // Retrieve selected seats array from sessionStorage
          var selectedSeatsArray = JSON.parse(sessionStorage.getItem('selectedSeats'));
      
          if (selectedSeatsArray && selectedSeatsArray.length > 0) {
              displaySelectedSeats(selectedSeatsArray);
          }
      };
      
      function displaySelectedSeats(selectedSeatsArray) {
          var container = document.getElementById('selected-seats-container');
          container.innerHTML = '';
      
          if (selectedSeatsArray && selectedSeatsArray.length > 0) {
              var paragraph = document.createElement('p');
              paragraph.textContent = selectedSeatsArray.join(', ');
              container.appendChild(paragraph);
          } else {
              container.textContent = 'No seats selected.';
          }
      }

      function sendOrderSummary() {
          // Assuming selectedSeatsArray is already available
          var selectedSeatsArray = JSON.parse(sessionStorage.getItem('selectedSeats'));
          var data = {
              movie_title: '{{ movie_title }}',
              selected_date: '{{ selected_date }}',
              mpaa_rating: '{{ mpaa_rating }}',
              show_time: '{{ show_time }}',
              ticket_quantity: '{{ ticket_quantity }}',
              
              selected_seats_list: JSON.stringify(selectedSeatsArray),
              total_price: '{{ total_price }}',
              booking_fees: '{{ booking_fees }}',
              tax: '{{ tax }}',
              discount: '{{ discount }}',
              total_new_price: '{{ total_new_price }}'
          };

          // Send the data via AJAX
          $.ajax({
              url: 'payments/',
              type: 'POST',
              contentType: 'application/json',
              data: JSON.stringify(data),
              success: function(response) {
                  // Handle success
              },
              error: function(xhr, status, error) {
                  // Handle error
              }
          });
      }

    </script>
  </head>
  <body data-user-logged-in="{{ request.user.is_authenticated|yesno:'true,false' }}" data-user-name="{% if user.is_authenticated %}{{ user.get_username }}{% endif %}">
    <div class="main-container" style="padding:20px;">
      <script src="{% static 'js/common.js' %}" async></script>
      <div class="rect">
        <h1>Order Summary</h1>
        <div class="summary-item">
          <h2>Movie Title:&nbsp;</h2>
          <p>{{ movie_title }}</p>
        </div>
        <div class="summary-item">
          <h2>Show Date:&nbsp;</h2>
          <p>{{ selected_date }}</p>
        </div>
        <div class="summary-item">
          <h2>Show Time:&nbsp;</h2>
          <p>{{ show_time }}</p>
        </div>
        <div class="summary-item">
          <h2>Number of Tickets:&nbsp;</h2>
          <p>{{ ticket_quantity }}</p>
        </div>
        <div class="summary-item">
          <h2>Selected Seats:&nbsp;</h2>
          {% comment %} <div name="selected-seats-container" id="selected-seats-container" ></div> {% endcomment %}
          
          <p>{{formatted_seats}}</p>
          
          {% comment %} <p>{{ seats|replace:"'":''|replace:'"':''|strip:"[]" }}</p> {% endcomment %}
        </div>
        <div class="summary-item">
          <h4>Sub-total:</h4>
          <p>${{ total_price }}</p>
        </div>
        <div class="summary-item">
          <h4>Booking Fees:</h4>
          <p>${{ booking_fees }}</p>
        </div>
        <div class="summary-item">
          <h4>Tax:</h4>
          <p>${{ tax }}</p>
        </div>
        <div class="summary-item">
          <h4>Discount:</h4>
          <p>${{ discount }}</p> 
          {% comment %} delete 00's here {% endcomment %}
        </div>
        <div class="summary-item">
          <h4>Total Price:</h4>
          <p>${{ total_new_price }}</p>
        </div>

        <form action="{% url 'apply_promo' movie_title selected_date show.start_time|date:'Y-m-d H:i:s' show.id%}" method="POST" id="promo-form" style="display:flex; flex-direction:column; align-content:center; width:18vw;">
          {% csrf_token %}
          <input type="hidden" name="movie_title" value="{{ movie_title }}">
          <input type="hidden" name="selected_date" value="{{ selected_date }}">
          <input type="hidden" name="show_time" value="{{ show_time }}">
          <input type="hidden" name="ticket_quantity" value="{{ ticket_quantity }}">
          <input type="hidden" name="selected_seats_list" value="{{ selected_seats_list }}">
          <input type="hidden" name="total_price" value="{{ total_price }}">
          <input type="hidden" name="formatted_seats" value="{{ formatted_seats }}">
          <input type="hidden" name="screen_id" value="{{ screen_id }}">
          <input type="hidden" name="show_id" value="{{show_id}}">
          <div class="promo-row">
            <input class="promo-box" type="text" id="promo_code" name="promo_code" placeholder="Promo Code">
            <button class="promo-btn" type="submit">Apply</button>
          </div>
      </form>
        <form action="{% url 'payments'%}" method="POST" style="display:flex; flex-direction:column; align-content:center; width:18vw;">
          {% csrf_token %}
          <input type="hidden" name="movie_title" value="{{ movie_title }}">
          <input type="hidden" name="selected_date" value="{{ selected_date }}">
          <input type="hidden" name="show_time" value="{{ show_time }}">
          <input type="hidden" name="mpaa_rating" value="{{ mpaa_rating }}">
          <input type="hidden" name="ticket_quantity" value="{{ ticket_quantity }}">
          <input type="hidden" name="selected_seats_list" value="{{ selected_seats_list }}">
          <input type="hidden" name="total_price" value="{{ total_price }}">
          <input type="hidden" name="booking_fees" value="{{ booking_fees }}">
          <input type="hidden" name="tax" value="{{ tax }}">
          <input type="hidden" name="total_new_price" value="{{ total_new_price }}">
          <input type="hidden" name="formatted_seats" value="{{ formatted_seats }}">
          <input type="hidden" name="screen_id" value="{{ screen_id }}">
          <input type="hidden" name="show_id" value="{{show_id}}">
          <br><br>
          <button class="proceed" type="submit" onclick="sendOrderSummary()">Proceed to Payment</button>
      </form>
      </div>
    </div>
  </body>
</html>

projectCinema/cinema/templates/html/e2.html
<!-- edit_profile.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;800&display=swap" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index 2.css' %}" />
    <link rel="stylesheet" href="{% static 'css/editprofile.css' %}" />
</head>
<body>
    <div class="main-container">
        <script src="{% static 'js/common.js' %}" async></script>
        <div class="flex-row-d">
            <div class="symbol-1"></div>
            <div class="symbol-2"></div>
            <div class="rectangle-1">
                <h2>Edit Profile</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <hr>
                    <h3>Change Password</h3>
                    {{ password_form.as_p }}
                    <button type="submit">Save Changes</button>
                </form>
            </div>
            <div class="symbol-3"></div>
            <div class="symbol-4"></div>
        </div>
    </div>
</body>
</html>

projectCinema/cinema/templates/html/email_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/img/home_pics/logo.png" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Confirmation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #000000; /* Black */
            color: #ffffff; /* White text */
            padding: 20px;
        }

        .container {
            background-color: #1e1e1e; /* Dark gray */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(255, 255, 255, 0.1); /* White shadow */
        }

        h1 {
            color: #ffffff; /* White */
            margin-top: 0;
        }

        h4 {
            margin-top: 10px;
            margin-bottom: 5px;
            color: #007bff; /* Blue */
        }

        p {
            margin-top: 5px;
            margin-bottom: 10px;
            color: #cccccc; /* Light gray */
        }

        a {
            text-decoration: none;
            color: #007bff; /* Blue */
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Order Confirmation</h1>
        <h4>Booking ID: {{ booking_id }}</h4>
        <img src="data:image/png;base64,{{ qr_code }}" alt="QR Code">
        <h4>Movie: {{ movie_title }}</h4>
        <h4>Show Time: {{ show_time }}</h4>
        <h4>Ticket Quantity: {{ ticket_quantity }}</h4>
        <h4>Seats: {{ seats }}</h4>
        <h4>Rating: {{ mpaa_rating }}</h4>
        <p></p>
    </div>
</body>

</html>

projectCinema/cinema/templates/html/email_verified.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/img/home_pics/logo.png" type="image/png">
    <link rel="stylesheet" href="{% static 'css/index 2.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/passchange.css' %}">
</head>
<body data-user-logged-in="{{ request.user.is_authenticated|yesno:'true,false' }}" data-user-name="{% if user.is_authenticated %}{{ user.get_username }}{% endif %}">
    <div class="main-container">
        <script src="{% static 'js/common.js' %}" async></script>
        <div class="rectangle">
            <h2 class="heading">Your email has been successfully verified.</h2>
            <h3 class="paragraph">You can now <a href="{% url 'login' %}">login</a>.</h3>
        </div>
    </div>
</body>
</html>

projectCinema/cinema/templates/html/invalid_link.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="/img/home_pics/logo.png" type="image/png">
    <meta charset="UTF-8">
    <title>Invalid Link</title>
</head>
<body>
    <h1>Invalid Verification Link</h1>
    <p>The verification link you clicked is invalid or has expired.</p>
</body>
</html>

projectCinema/cinema/templates/html/new_promo_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/img/home_pics/logo.png" type="image/png">
    <title>New Promo Code Available!</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #000000; /* Black */
            color: #ffffff; /* White text */
            padding: 20px;
        }

        .container {
            background-color: #1e1e1e; /* Dark gray */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(255, 255, 255, 0.1); /* White shadow */
        }

        h1 {
            color: #ffffff; /* White */
            margin-top: 0;
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }

        li strong {
            color: #007bff; /* Blue */
        }

        p {
            margin-top: 10px;
            margin-bottom: 10px;
            color: #cccccc; /* Light gray */
        }

        a {
            text-decoration: none;
            color: #007bff; /* Blue */
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>New Promo Code Available!</h1>
        <p>A new promo code has been added:</p>
        <ul>
            <li><strong>Code:</strong> {{ promo_code.code }}</li>
            <li><strong>Discount Type:</strong> {{ promo_code.get_discount_type_display }}</li>
            <li><strong>Discount Value:</strong> {{ promo_code.discount_value }}</li>
            <li><strong>Valid From:</strong> {{ promo_code.valid_from }}</li>
            <li><strong>Valid To:</strong> {{ promo_code.valid_to }}</li>
        </ul>
        <p>Visit our website to avail of this promotion!</p>
    </div>
</body>
</html>

projectCinema/cinema/templates/html/password_reset_email.html
{% autoescape off %}
Click the following link to reset your password:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If you didn't request a password reset, please ignore this email.
{% endautoescape %}

projectCinema/cinema/templates/html/verification_email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/img/home_pics/logo.png" type="image/png">
    <title>Verification Email</title>
</head>
<body>
    <h2>Hello {{ user.username }},</h2>
    <div class="container">
        {% comment %} <h1>Email Verification</h1> {% endcomment %}
        {% comment %} <p>Hello {{ user.username }},</p> {% endcomment %}
        <p>Please click the following link to verify your email address:</p>
        <a href="{{ verification_url }}">{{ verification_url }}</a>
    </div>
</body>

</html>